use_frameworks!

target 'YangDefaultPages_Example' do
  pod 'YangDefaultPages', :path => '../'
  pod 'SnapKit'
  
  target 'YangDefaultPages_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'YangDefaultPages_Example'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
    end
